name: museotoolbox
dependencies:
        - python=3.7
        - GDAL
        - numpy
        - scikit-learn
        - scipy
        - pip:
           - nbsphinx
           - sphinx-rtd-theme
           - sphinx-gallery

