name: museotoolbox
dependencies:
        - python=3.7
        - GDAL
        - numpy
        - scikit-learn
        - scipy
        - matplotlib
        - recommonmark
        - sphinx>=1.4
        - numpydoc
        - sphinx-rtd-theme
        - ipykernel
        - nbsphinx
        - sphinx-gallery
