language: python
matrix:
#    allow_failures:
#        - os: osx
    include:
#        - os: osx
#          language: generic
        - os: linux
          sudo: required
          python: 3.5
        - os: linux
          sudo: required
          python: 3.6
        - os: linux
          sudo: required
          python: 3.7

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - python setup.py develop
