dist: bionic
language: python
os : linux


addons:
   apt:
     packages:
     - libgdal-dev
matrix:
  include:
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7

before_install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get --quiet update
  - sudo apt-get install --yes libgdal-dev gdal-bin
install:
  - pip install gdal==`gdal-config --version`
  - pip install -r requirements.txt
  - pip install .
  - pip install --user codecov
  - pip install pytest-cov pytest

script:
- python setup.py develop
- py.test  --cov-report term --cov=test/

deploy:
  provider: pypi
  user: "karasiak"
  password:
    secure: 7NeKw+T+tO7LWvwjgj1agHIo8zQlA33bkg9x6pQ4zXd24ZJ4XDhqnGSxG9NKr9pP9l9PwDrPZIIW50JeBWula+JXQxtRj80LNJB8ySJVn3BEdLojxUMthVvOtdUqzqFME5iFpP6SEdUrODMHXJa18tCP5QN2XHUWEixmmqrbFg8JYgg6nswVmmCHpXor5h9LW1V0bJ1uOThmpjhXUhKx7xM6lcXJssC91Ghmkh1SApNuK3Ah8ir92HK53VSdQScK8QAHIpvWGbTLhbt7C4IuwDFERgDIbOec6L9UxOePMXmIF/5wu+mlQeVzFV5DiFBJ0U+fDEqg1PTKifM9KQmOtBX8iFVyiZmwqM6wRJjt83C5j4VKDj8vs8Y9dGkmOobRNlE3HdEekB69mj5177oCpOSZtgntkbR/9wfEK7j4qnj/mALaKx9mYKdI9nRepEnnocp6R2aGvZD0BxSwRWxjgubfolsG3mBHBRhjog5pVOcC4de3aPwZKxWTls2AIMP47lxocKnpHWTzKAtuPEo4w/Y2IaFXbk0EQleC6BLHAWi7DbAYct7/6Ju7VOdm80ko0To4PQ+9fzpSZndcAxf1cEys0OaVcQPJ9XjxfvzHUz1OXqQKzZe5tfAxFS6q6rbMV4J9zNRP+xX8rOhmB4HajBmBfIEcz/Avt4R+pl5lIeo=
  on:
    tags: true
    branch: master
  skip_existing: true

after_succes:
 - codecov 
